use crate::model::*;

pub fn render_reason_codes(tuple: &TupleSpec) -> String {
    let reason_variants = tuple
        .reason_codes
        .iter()
        .map(|r| format!("    {},", r))
        .collect::<Vec<_>>()
        .join("\n");
    let severity_variants = tuple
        .severities
        .iter()
        .map(|s| format!("    {},", s))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "// @generated by tools/specgen. DO NOT EDIT.\n\nuse serde::{{Deserialize, Serialize}};\n\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]\npub enum Severity {{\n{}\n}}\n\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]\npub enum ReasonCode {{\n{}\n}}\n",
        severity_variants, reason_variants
    )
}

pub fn render_thresholds(
    state: &StateSpec,
    flow: &FlowSpec,
    energy: &EnergySpec,
    guarantees: &GuaranteesSpec,
    inv: &InvariantsSpec,
) -> String {
    format!(
        "// @generated by tools/specgen. DO NOT EDIT.\n\npub const FRAME: &str = \"{}\";\npub const MAX_SPEED_MPS: f64 = {:?};\npub const MAX_BANK_DEG: f64 = {:?};\npub const MIN_ALTITUDE_M: f64 = {:?};\npub const MIN_SOC_PERCENT: f64 = {:?};\npub const MAX_INPUT_AGE_MS: u64 = {};\npub const MAX_TICK_INTERVAL_MS: u64 = {};\npub const DEADLINE_MS: u64 = {};\npub const MAX_ROLL_RATE_DPS: f64 = {:?};\npub const MAX_PITCH_RATE_DPS: f64 = {:?};\npub const MAX_YAW_RATE_DPS: f64 = {:?};\npub const MAX_CLIMB_RATE_MPS: f64 = {:?};\n",
        state.frame,
        state.max_speed_mps,
        inv.max_bank_deg,
        inv.min_altitude_m,
        energy.min_soc_percent,
        guarantees.max_input_age_ms,
        guarantees.max_tick_interval_ms,
        guarantees.deadline_ms,
        flow.max_roll_rate_dps,
        flow.max_pitch_rate_dps,
        flow.max_yaw_rate_dps,
        flow.max_climb_rate_mps
    )
}

pub fn render_profile(profile: &ProfileSpec) -> String {
    format!(
        "// @generated by tools/specgen. DO NOT EDIT.\n\npub const PROFILE_NAME: &str = \"{}\";\npub const CONTROL_HZ: u64 = {};\npub const PROFILE_DEADLINE_MS: u64 = {};\npub const CAP_VTOL: bool = {};\npub const CAP_FIXED_WING: bool = {};\n",
        profile.name,
        profile.timing.control_hz,
        profile.timing.deadline_ms,
        profile.capabilities.vtol,
        profile.capabilities.fixed_wing
    )
}
