// @generated by tools/specgen. DO NOT EDIT.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Severity {
    Info,
    Warning,
    Critical,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ReasonCode {
    StateInvalidFrame,
    StateOutOfBounds,
    FlowConstraintViolation,
    EnergyBudgetExceeded,
    TemporalGuaranteeViolation,
    InvariantViolation,
    InputStale,
    DeadlineMiss,
}
