// @generated by tools/specgen. DO NOT EDIT.

pub const FRAME: &str = "NED";
pub const MAX_SPEED_MPS: f64 = 120.0;
pub const MAX_BANK_DEG: f64 = 60.0;
pub const MIN_ALTITUDE_M: f64 = 5.0;
pub const MIN_SOC_PERCENT: f64 = 20.0;
pub const MAX_INPUT_AGE_MS: u64 = 100;
pub const MAX_TICK_INTERVAL_MS: u64 = 20;
pub const DEADLINE_MS: u64 = 10;
pub const MAX_ROLL_RATE_DPS: f64 = 120.0;
pub const MAX_PITCH_RATE_DPS: f64 = 100.0;
pub const MAX_YAW_RATE_DPS: f64 = 80.0;
pub const MAX_CLIMB_RATE_MPS: f64 = 8.0;
