// @generated by tools/specgen. DO NOT EDIT.

pub const PROFILE_NAME: &str = "uas-small";
pub const CONTROL_HZ: u64 = 50;
pub const PROFILE_DEADLINE_MS: u64 = 10;
pub const CAP_VTOL: bool = false;
pub const CAP_FIXED_WING: bool = true;
